---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  CF_MANIFEST_HOST:

inputs:
  - name: pcfdemo

outputs:
  - name: prepare-integration

run:
  path: pcfdemo/ci/tasks/prepare-integration.sh
  args: [
    --input-dir, pcfdemo,
    --output-dir, prepare-integration,
    --input-manifest, pcfdemo/manifest.yml,
    --artifactId, pcf-demo,
    --packaging, war
  ]
