---
resources:
  - name: pcfdemo
    type: git
    source:
      uri: {{github-uri}}
      branch: {{github-branch}}

  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true

jobs:
  - name: unit-test
    public: true
    plan:
      - get: pcfdemo
        trigger: true
      - task: unit
        file: pcfdemo/ci/tasks/unit.yml
        params: &MAVENPARAMS
          MAVEN_OPTS: {{maven-opts}}
          MAVEN_CONFIG: {{maven-config}}

  - name: ft-integration-test
    serial: true
    plan:
      - get: pcfdemo
        passed: [unit-test]
      - task: ft
        file: pcfdemo/ci/tasks/ft.yml
        params:
          CF_MANIFEST_HOST: {{cf-manifest-host}}
      - put: cf
        params:
          manifest: build/manifest.yml
      - task: integration
        file: pcfdemo/ci/tasks/integration.yml
        params:
          <<: *MAVENPARAMS

 - name: st-integration-test
    serial: true
    plan:
      - get: pcfdemo
        passed: [ft-integration-test]
      - task: st
        file: pcfdemo/ci/tasks/st.yml
        params:
          CF_MANIFEST_HOST: {{cf-manifest-host}}
      - put: cf
        params:
          manifest: build/manifest.yml
      - task: integration
        file: pcfdemo/ci/tasks/integration.yml
        params:
          <<: *MAVENPARAMS

